tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"
brew "anyenv"
brew "bitwarden-cli"
brew "fd"
brew "fzf"
brew "git"
brew "git-lfs"
brew "neovim"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rustup-init"
brew "tmux"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
