tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
brew "fd"
brew "fzf"
brew "git"
brew "libpng"
brew "mas"
brew "neovim"
brew "nodenv"
brew "pyenv"
brew "ripgrep"
brew "tmux"
cask "adobe-creative-cloud"
cask "alfred"
cask "bitwarden"
cask "brave-browser"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-noto-sans-cjk"
cask "font-noto-sans-cjk-jp"
cask "iterm2"
cask "karabiner-elements"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "notion"
cask "sublime-text"
cask "transmit"
cask "visual-studio-code"
cask "zoom"
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Stay", id: 435410196
mas "Xcode", id: 497799835
