# 起動時に読み込まれるプラグイン

[[plugins]]
repo = 'Shougo/dein.vim'


######################  Colors  ########################

# [[plugins]] # solarized
# repo = 'altercation/vim-colors-solarized'

[[plugins]] # Gruvbox
repo = 'morhetz/gruvbox'

########################################################

##################  Syntax Highlight ###################

### Javascript
#
[[plugins]] # jsの色付け
repo = 'othree/yajs.vim'

[[plugins]] # jsの色付け
repo = 'othree/es.next.syntax.vim'

[[plugins]] # シンタックスハイライト全般
repo = 'sheerun/vim-polyglot'

# [[plugins]] # nunjucks
# repo  = 'Glench/Vim-Jinja2-Syntax'

########################################################


##################  Language support  ##################

# Language
[[plugins]] # Html5
repo  = 'othree/html5.vim'

[[plugins]] # for vue
repo = 'leafOfTree/vim-vue-plugin'

[[plugins]] # for vue
repo = 'posva/vim-vue'


########################################################


##################  Syntax check ###################

# [[plugins]]
# repo = 'dense-analysis/ale'

########################################################


##################  Utilitis  ###################


[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'a796c43f'
# rev = '''
# {'release': 'a796c43f'}
# '''
merged = '0'

# ファイラー系

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
# hook_add = '''
#   command! -bang -nargs=* Rg
#     \ call fzf#vim#grep(
#     \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
#     \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
# '''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]] # editorconfigを使う
repo = 'editorconfig/editorconfig-vim'

[[plugins]] #コメント
repo = 'tomtom/tcomment_vim'

[[plugins]] # vim-expand-region
repo = 'terryma/vim-expand-region'

[[plugins]] # 閉じ括弧やコーテーションを補完
repo = 'cohama/lexima.vim'

[[plugins]] # dot repeateをマクロ単位に
repo = 'tpope/vim-repeat'

[[plugins]] # ステータスバー装飾
repo = 'vim-airline/vim-airline'

[[plugins]] # Emmet
repo = 'mattn/emmet-vim'


########################################################


##################  Git  ###################

[[plugins]]
repo = 'airblade/vim-gitgutter'

########################################################




