# 起動時に読み込まれるプラグイン

[[plugins]]
repo = 'Shougo/dein.vim'







######################  Colors  ########################
#
# [[plugins]] # hybrid
# repo = 'w0ng/vim-hybrid'

[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'

########################################################






##################  Language support  ##################

# Language
[[plugins]] # Html5
repo  = 'othree/html5.vim'

[[plugins]] # nunjucks
repo  = 'lepture/vim-jinja'

[[plugins]] # for vue
repo = 'leafOfTree/vim-vue-plugin'

[[plugins]] # for vue
repo = 'posva/vim-vue'


########################################################






##################  Syntax Highlight ###################

### Javascript
#
[[plugins]] # jsの色付け
repo = 'othree/yajs.vim'

[[plugins]] # jsの色付け
repo = 'othree/es.next.syntax.vim'

[[plugins]] # シンタックスハイライト全般
repo = 'sheerun/vim-polyglot'

########################################################







##################  Syntax check ###################

[[plugins]]
repo = 'dense-analysis/ale'

########################################################







##################  Utilitis  ###################

# ファイラー系
[[plugins]] # vim 用の統合ユーザインターフェース
repo = 'Shougo/denite.nvim'

# [[plugins]]
repo = 'Shougo/defx.nvim'

# [[plugins]]
# repo = 'scrooloose/nerdtree'

[[plugins]] # ステータスバー装飾
repo = 'vim-airline/vim-airline'


[[plugins]]
repo = 'tpope/vim-surround'
#
[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]] # editorconfigを使う
repo = 'editorconfig/editorconfig-vim'

# [[plugins]]
# repo = 'tpope/vim-commentary'

[[plugins]] #コメント
repo = 'tomtom/tcomment_vim'

[[plugins]] # Emmet
repo = 'mattn/emmet-vim'


[[plugins]] # vim-expand-region
repo = 'terryma/vim-expand-region'


# [[plugins]] # マルチカーソル
# repo = 'terryma/vim-multiple-cursors'
# repo = 'mg979/vim-visual-multi'

[[plugins]] # 閉じ括弧やコーテーションを補完
repo = 'cohama/lexima.vim'

##補完系
# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# on_event = 'InsertEnter'
# hook_source = '''
#   let g:deoplete#enable_at_startup = 1
#   call deoplete#custom#option({
#        \   'auto_complete_delay': 100,
#        \ })
#   "入力からポップアップ表示までのdealy[ms]
#   "大文字小文字を区別
# '''

[[plugins]] # dot repeateをマクロ単位に
repo = 'tpope/vim-repeat'

# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# build = 'bash install.sh'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = 'call coil398#init#coc#hook_source()'

# [[plugins]]
# repo = 'Shougo/neosnippet.vim'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'honza/vim-snippets'

# [[plugins]]
# repo = 'prettier/vim-prettier'
# build = 'npm install'
# on_ft    = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']

########################################################



##################  Git  ###################

# [[plugins]]
# repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'



########################################################































#[[plugins]]
#repo = 'rust-lang/rust.vim'
#on_ft = 'rust'


#on_source = '~/.config/nvim/plugins/NERDTree.rc.vim'

#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'










## [[plugins]] # ファイラー
## repo = 'ctrlpvim/ctrlp.vim'



#[[plugins]] # 複数選択
#repo = 'terryma/vim-multiple-cursors'

## [[plugins]] # 変数ハイライト
## repo = 'dominikduda/vim_current_word'






# [[plugins]]
# repo = 'blueyed/vim-diminactive'
#
#
#
#
#
#
#
#
#
#
